/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rsa;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;
import jdk.internal.org.jline.terminal.TerminalBuilder;
import org.apache.poi.openxml4j.exceptions.InvalidFormatException;
import org.apache.poi.openxml4j.opc.OPCPackage;
import org.apache.poi.xwpf.extractor.XWPFWordExtractor;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
 

public class RSAthucong extends javax.swing.JFrame {

    /**
     * Creates new form RSAthucong
     */
    static BigInteger ciphertext;

    static RSAint rsa;
    public RSAthucong() {
        initComponents();
        jProgressBar1.setStringPainted(true);
        jProgressBar1.setForeground(Color.blue);

        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        
        btnsaveEnFile.setEnabled(false);
        btnsaveDeFile.setEnabled(false);
        
        rsa = new RSAint();
        this.setLocation(300, 50);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTaoKhoa = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtP = new javax.swing.JTextField();
        txtQ = new javax.swing.JTextField();
        txtE = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        txtphiN = new javax.swing.JTextField();
        txtD = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtInputEn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtEncrypt = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        btnsaveEnFile = new javax.swing.JButton();
        btnopenEnFile = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtDecrypt = new javax.swing.JTextArea();
        btnsaveDeFile = new javax.swing.JButton();
        btnopenDeFile = new javax.swing.JButton();
        txtInputDe = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtTaoKhoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTaoKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/vcard_key.png"))); // NOI18N
        txtTaoKhoa.setText("Tạo khóa");
        txtTaoKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaoKhoaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/key_start.png"))); // NOI18N
        jLabel19.setText("Tạo khóa thủ công");

        jLabel2.setText("p=");

        jLabel3.setText("q=");

        jLabel9.setText("n=");

        jLabel12.setText("e=");

        jLabel16.setText("phi(n)=");

        jLabel17.setText("d=");

        txtP.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPActionPerformed(evt);
            }
        });

        txtQ.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQActionPerformed(evt);
            }
        });

        txtE.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNActionPerformed(evt);
            }
        });

        txtphiN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtphiN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphiNActionPerformed(evt);
            }
        });

        txtD.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel12)
                            .addComponent(jLabel17))
                        .addGap(260, 260, 260))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtphiN, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTaoKhoa)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(txtphiN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(txtTaoKhoa)
                .addGap(15, 15, 15))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, 437));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Đầu vào");

        txtInputEn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtInputEn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputEnActionPerformed(evt);
            }
        });

        jLabel10.setText(" ");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Kết quả sau mã hóa");

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/shield_start.png"))); // NOI18N
        jButton4.setText("Mã Hóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtEncrypt.setColumns(20);
        txtEncrypt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtEncrypt.setLineWrap(true);
        txtEncrypt.setRows(5);
        txtEncrypt.setWrapStyleWord(true);
        jScrollPane10.setViewportView(txtEncrypt);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/user_mature.png"))); // NOI18N
        jLabel20.setText("Mã hóa");

        btnsaveEnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/disk_black.png"))); // NOI18N
        btnsaveEnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveEnFileActionPerformed(evt);
            }
        });

        btnopenEnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/folder_up.png"))); // NOI18N
        btnopenEnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenEnFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel20))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnopenEnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtInputEn, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsaveEnFile)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel20)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnopenEnFile))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtInputEn)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(btnsaveEnFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 310, 440));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Đầu vào");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Kết quả sau giải mã");

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/shield_rainbow.png"))); // NOI18N
        jButton5.setText("Giải mã");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/shield_start.png"))); // NOI18N
        jLabel1.setText("Giải mã");

        txtDecrypt.setColumns(20);
        txtDecrypt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtDecrypt.setLineWrap(true);
        txtDecrypt.setRows(5);
        txtDecrypt.setWrapStyleWord(true);
        jScrollPane12.setViewportView(txtDecrypt);

        btnsaveDeFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/disk_black.png"))); // NOI18N
        btnsaveDeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveDeFileActionPerformed(evt);
            }
        });

        btnopenDeFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/folder_up.png"))); // NOI18N
        btnopenDeFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnopenDeFileActionPerformed(evt);
            }
        });

        txtInputDe.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtInputDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputDeActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("d");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnsaveDeFile))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnopenDeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtInputDe))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(btnopenDeFile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtInputDe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnsaveDeFile, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 310, 437));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel15.setText("MÃ HÓA VÀ GIẢI MÃ RSA");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, 70));
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 114, 18));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsa/reset.png"))); // NOI18N
        jButton9.setText("RESET");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 102, 53));

        jButton2.setText("Chuyển sang tạo khóa tự động");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtTaoKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaoKhoaActionPerformed
        // TODO add your handling code here:
        
        jProgressBar1.setIndeterminate(true);
        
        String inputP = txtP.getText();
    String inputQ = txtQ.getText();

    if (inputP == null || inputP.isEmpty() || inputQ == null || inputQ.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập dữ liệu cho cả P và Q", "Thông báo", JOptionPane.ERROR_MESSAGE);
        txtP.setText("");
        txtQ.setText("");
        return; // Kết thúc sự kiện ngay lập tức
    }

    try {
        BigInteger p = new BigInteger(inputP);
        BigInteger q = new BigInteger(inputQ);

        if (!rsa.isPrime(p)) {
            JOptionPane.showMessageDialog(null, "Giá trị P không phải là số nguyên tố, vui lòng nhập lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtP.setText("");
            txtQ.setText("");
            return; // Kết thúc sự kiện ngay lập tức
        } else if (!rsa.isPrime(q)) {
            JOptionPane.showMessageDialog(null, "Giá trị Q không phải là số nguyên tố, vui lòng nhập lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtP.setText("");
            txtQ.setText("");
            return; // Kết thúc sự kiện ngay lập tức
        } else if (p.equals(q)) {
            JOptionPane.showMessageDialog(null, "Giá trị P và Q phải khác nhau, vui lòng nhập lại", "Thông báo", JOptionPane.ERROR_MESSAGE);
            txtP.setText("");
            txtQ.setText("");
            return; // Kết thúc sự kiện ngay lập tức
        } else {
            // Nếu tất cả điều kiện hợp lệ, tạo khóa RSA
            rsa.generateKeyPair(p, q);
            JOptionPane.showMessageDialog(null, "Khóa đã được tạo thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Vui lòng nhập số hợp lệ cho P và Q", "Thông báo", JOptionPane.ERROR_MESSAGE);
        txtP.setText("");
        txtQ.setText("");
        return; // Kết thúc sự kiện ngay lập tức
    }
        



        
        
        
        
        
        
        
        txtN.setText(rsa.getN().toString());
        txtE.setText(rsa.getE().toString());
        txtphiN.setText(rsa.getphiN().toString());
        txtD.setText(rsa.getD().toString());

        jButton4.setEnabled(true);
        jButton5.setEnabled(true);

        jProgressBar1.setMaximum(100);
        jProgressBar1.setValue(200);
        jProgressBar1.setIndeterminate(false);
    }//GEN-LAST:event_txtTaoKhoaActionPerformed

    private void txtInputEnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputEnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputEnActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        String filename = txtInputEn.getText();// change accordingly
        if ("".equals(filename)) {
            jProgressBar1.setIndeterminate(true);
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập dữ liệu đầu vào", "Thông báo", JOptionPane.ERROR_MESSAGE);
            jProgressBar1.setMaximum(200);
            jProgressBar1.setValue(0);
            jProgressBar1.setIndeterminate(false);
        } else {
            try {
                jProgressBar1.setIndeterminate(true);
                txtEncrypt.setText(rsa.encrypt(filename));
                btnsaveEnFile.setEnabled(true);
                jProgressBar1.setMaximum(200);
                jProgressBar1.setValue(200);
                jProgressBar1.setIndeterminate(false);
                txtInputDe.setText(txtEncrypt.getText());
                jTextField1.setText(rsa.getD().toString());
                JOptionPane.showMessageDialog(null, "Bạn đã mã hóa thành công!");

            } catch (Exception ex) {
                Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnsaveEnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveEnFileActionPerformed
        // TODO add your handling code here:
        String str = new String(txtEncrypt.getText());
        try {
            OutputWrite(getSaveLocation(), str, "Encrypt.txt");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnsaveEnFileActionPerformed

    private void btnopenEnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenEnFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fChon = new JFileChooser();
        FileNameExtensionFilter fLocTxt = new FileNameExtensionFilter("txt", "txt");
        FileNameExtensionFilter fLocDoc = new FileNameExtensionFilter("docx", "docx");
        fChon.addChoosableFileFilter(fLocTxt);
        fChon.addChoosableFileFilter(fLocDoc);
        fChon.setMultiSelectionEnabled(false);
        int x = fChon.showDialog(this, "Tải file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fChon.getSelectedFile();
            boolean checkdocx;
            if (f.getName().contains(".txt")) {
                //           txtLinkFileMH.setText(f.getPath());
                String link=f.getPath();
                try {
                    File nd = new File(link);
                    Scanner sc = new Scanner(nd);
                    String content = "";
                    while (sc.hasNextLine()) {
                        content += sc.nextLine() + "\r\n";
                    }
                    txtInputEn.setText(content);
                    sc.close();
                    JOptionPane.showMessageDialog(this, "Tải lên File hoàn tất!");
                } catch (FileNotFoundException ex) {
                    System.out.println("Error!");
                    //                checkDocx = false;
                    JOptionPane.showMessageDialog(this, "Tải lên File thất bại!");
                }
            } else if (f.getAbsolutePath().contains(".docx")) {
                String link=f.getPath();
                try {
                    FileInputStream fis = new FileInputStream(link);
                    XWPFDocument document = new XWPFDocument(OPCPackage.open(fis));
                    XWPFWordExtractor wordExtractor = new XWPFWordExtractor(document);
                    txtInputEn.setText(wordExtractor.getText());
                    wordExtractor.close();
                    document.close();
                    //                checkDocx = true;
                    JOptionPane.showMessageDialog(this, "Tải lên File hoàn tất!");
                } catch (HeadlessException | IOException | InvalidFormatException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnopenEnFileActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        if ("".equals(txtInputDe.getText())) {
            jProgressBar1.setIndeterminate(true);
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập dữ liệu đầu vào", "Thông báo", JOptionPane.ERROR_MESSAGE);
            jProgressBar1.setMaximum(200);
            jProgressBar1.setValue(0);
            jProgressBar1.setIndeterminate(false);
        } else {
            try {
                jProgressBar1.setIndeterminate(true);
                txtDecrypt.setText(rsa.decrypt(txtInputDe.getText()));
                jProgressBar1.setMaximum(200);
                jProgressBar1.setValue(200);
                jProgressBar1.setIndeterminate(false);
                if (txtInputEn.getText().equals(txtDecrypt.getText())) {
                    JOptionPane.showMessageDialog(null, "Giải mã đúng!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                    btnsaveDeFile.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Giải mã sai", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    
     public void OutputWrite(File saveLocation, String name, String decrypttxt)
            throws FileNotFoundException {

        PrintWriter file  = new PrintWriter(new FileOutputStream(new File(saveLocation, name)));
        file.println(txtDecrypt.getText());
        file.close();

    }
    
    private File getFileLocation() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showSaveDialog(this);

        if (result == chooser.APPROVE_OPTION) {
            return chooser.getSelectedFile();
        } else {
            return null;
        }
    }
     
    private File getSaveLocation() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showSaveDialog(this);

        if (result == chooser.APPROVE_OPTION) {
            return chooser.getSelectedFile();
        } else {
            return null;
        }
    }
    
    private void btnsaveDeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveDeFileActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        
        String str = new String(txtDecrypt.getText());
        try {
            OutputWrite(getSaveLocation(), "Decrypt.txt", str);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormDSRSA.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnsaveDeFileActionPerformed

    private void btnopenDeFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnopenDeFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fChon = new JFileChooser();
        FileNameExtensionFilter fLocTxt = new FileNameExtensionFilter("txt", "txt");
        FileNameExtensionFilter fLocDoc = new FileNameExtensionFilter("docx", "docx");
        fChon.addChoosableFileFilter(fLocTxt);
        fChon.addChoosableFileFilter(fLocDoc);
        fChon.setMultiSelectionEnabled(false);
        int x = fChon.showDialog(this, "Tải file");
        if (x == JFileChooser.APPROVE_OPTION) {
            File f = fChon.getSelectedFile();
            boolean checkdocx;
            if (f.getName().contains(".txt")) {
                //           txtLinkFileMH.setText(f.getPath());
                String link=f.getPath();
                try {
                    File nd = new File(link);
                    Scanner sc = new Scanner(nd);
                    String content = "";
                    while (sc.hasNextLine()) {
                        content += sc.nextLine() + "\r\n";
                    }
                    txtInputDe.setText(content);
                    sc.close();
                    JOptionPane.showMessageDialog(this, "Tải lên File hoàn tất!");
                } catch (FileNotFoundException ex) {
                    System.out.println("Error!");
                    //                checkDocx = false;
                    JOptionPane.showMessageDialog(this, "Tải lên File thất bại!");
                }
            } else if (f.getAbsolutePath().contains(".docx")) {
                String link=f.getPath();
                try {
                    FileInputStream fis = new FileInputStream(link);
                    XWPFDocument document = new XWPFDocument(OPCPackage.open(fis));
                    XWPFWordExtractor wordExtractor = new XWPFWordExtractor(document);
                    txtInputEn.setText(wordExtractor.getText());
                    wordExtractor.close();
                    document.close();
                    //                checkDocx = true;
                    JOptionPane.showMessageDialog(this, "Tải lên File hoàn tất!");
                } catch (HeadlessException | IOException | InvalidFormatException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnopenDeFileActionPerformed

    private void txtInputDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputDeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInputDeActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jProgressBar1.setValue(0);
        txtInputEn.setText("");
        txtInputDe.setText("");

        txtEncrypt.setText("");
        txtDecrypt.setText("");

        jButton4.setEnabled(false);
        jButton5.setEnabled(false);

        btnsaveEnFile.setEnabled(false);
        btnsaveDeFile.setEnabled(false);
        txtP.setText("");
        txtQ.setText("");
        txtN.setText("");
        txtE.setText("");
        txtphiN.setText("");
        txtD.setText("");

    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQActionPerformed

    private void txtPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPActionPerformed

    private void txtphiNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphiNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphiNActionPerformed

    private void txtNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FormDSRSA formDSRSA=new FormDSRSA();
        formDSRSA.setVisible(true);
        formDSRSA.pack();
        formDSRSA.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RSAthucong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RSAthucong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RSAthucong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RSAthucong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RSAthucong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnopenDeFile;
    private javax.swing.JButton btnopenEnFile;
    private javax.swing.JButton btnsaveDeFile;
    private javax.swing.JButton btnsaveEnFile;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtD;
    private javax.swing.JTextArea txtDecrypt;
    private javax.swing.JTextField txtE;
    private javax.swing.JTextArea txtEncrypt;
    private javax.swing.JTextField txtInputDe;
    private javax.swing.JTextField txtInputEn;
    private javax.swing.JTextField txtN;
    private javax.swing.JTextField txtP;
    private javax.swing.JTextField txtQ;
    private javax.swing.JButton txtTaoKhoa;
    private javax.swing.JTextField txtphiN;
    // End of variables declaration//GEN-END:variables
}
